apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-product1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: pc-product1
    spec:
      containers:
      - name: pc-product1
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-product:v1.1.56-test
        ports: 
        - containerPort: 8017
      imagePullSecrets:
      - name: k8simagelogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-product-svc
spec:
  selector:
    run: pc-product1
  type: NodePort
  ports:
    - nodePort: 30017
      port: 8017
      targetPort: 8017
