apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-product
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pc-product
    spec:
      containers:
      - name: pc-product
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-product:v1.1.3
        ports: 
        - containerPort: 8017
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-product-svc
spec:
  selector:
    run: pc-product
  type: NodePort
  ports:
    - nodePort: 30017
      port: 8017
      targetPort: 8017
