server:
  port: 8011
swagger:
    enabled: true
    title: 美容邦系统管理模块-App微服务
    description: 更多系统管理模块微服务在线API文档稍后发布
    version: 1.0
    license: Apache License, Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    base-package: com.union.aimei.pc.system
    base-path: /**
    exclude-path: /error
#spring:
#  profiles:
#    active: @profileActive@