apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-learn
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pc-learn
    spec:
      containers:
      - name: pc-learn
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-learn:v1.1.3
        ports: 
        - containerPort: 8031
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-learn-svc
spec:
  selector:
    run: pc-learn
  type: NodePort
  ports:
    - nodePort: 30020
      port: 8031
      targetPort: 8031
