apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-im
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pc-im
    spec:
      containers:
      - name: pc-im
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-im:v1.1.3
        ports: 
        - containerPort: 8015
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-im-svc
spec:
  selector:
    run: pc-im
  type: NodePort
  ports:
    - nodePort: 30021
      port: 8015
      targetPort: 8015
