apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-umeng
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pc-umeng
    spec:
      containers:
      - name: pc-umeng
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-umeng:v1.1.3
        ports: 
        - containerPort: 8025
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-umeng-svc
spec:
  selector:
    run: pc-umeng
  type: NodePort
  ports:
    - nodePort: 30014
      port: 8025
      targetPort: 8025
