spring:
  application:
    name: admin-server
  rabbitmq:
     host: 47.106.90.37
     port: 5672
     username: guest

     password: aimeirabbit123456!
  boot:
    admin:
      turbine:
#        clusters: default
##设置turbine端点的service-id，由于目前turbine功能已经集成到了admin-cloud-server程序中，所以这里填写的是该程序注册到注册中心的service-Id
#        location: http://120.79.42.13:${turbine.stream.port}/turbine.stream
#        location: http://localhost:${turbine.stream.port}/turbine.stream
        location: http://120.78.94.124:${turbine.stream.port}/turbine.stream
#        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
#turbine:
#  clusterNameExpression: new String("default")
##设置需要监控的serviceId
#  app-config: app-api
turbine:
  stream:
    port: 8088

server:
  port: 8090
eureka:
  client:
    serviceUrl:
        defaultZone: http://120.78.94.124:8000/eureka/,http://39.108.187.198:8000/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@
logging:
  level:
    root: error


