apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: gateway-server
    spec:
      containers:
      - name: gateway-server
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/gateway-server:v1.1.3
        ports: 
        - containerPort: 8005
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-svc
spec:
  selector:
    run: gateway-server
  type: NodePort
  ports:
    - nodePort: 30037
      port: 8005
      targetPort: 8005
