apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-order
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: app-order
    spec:
      containers:
      - name: app-order
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/app-order:v1.1.56-test
        ports: 
        - containerPort: 8012
      imagePullSecrets:
      - name: k8simagelogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: app-order-svc
spec:
  selector:
    run: app-order
  type: NodePort
  ports:
    - nodePort: 30031
      port: 8012
      targetPort: 8012
