apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: admin-server
    spec:
      containers:
      - name: admin-server
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/admin-server:v1.1.56-test
        ports: 
        - containerPort: 8090
      imagePullSecrets:
      - name: k8simagelogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server-svc
spec:
  selector:
    run: admin-server
  type: NodePort
  ports:
    - nodePort: 30038
      port: 8090
      targetPort: 8090
