server:
  port: 8006
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://120.78.208.179:8000/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: http://120.79.131.10:8888/beautybond/config.git
          search-paths: config-repo/*
          username: gaowei
          password: gaowei123
          clone-on-start: true
          force-pull: true
  rabbitmq:
        host: 120.78.208.179
        port: 5672
        username: guest
        password: guest
management:
  security:
    enabled: false
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@
