apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-financial
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: pc-financial
    spec:
      containers:
      - name: pc-financial
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-financial:v1.1.56-test
        ports: 
        - containerPort: 8023
      imagePullSecrets:
      - name: k8simagelogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-financial-svc
spec:
  selector:
    run: pc-financial
  type: NodePort
  ports:
    - nodePort: 30022
      port: 8023
      targetPort: 8023
