apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-member
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pc-member
    spec:
      containers:
      - name: pc-member
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-member:v1.1.3
        ports: 
        - containerPort: 8021
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-member-svc
spec:
  selector:
    run: pc-member
  type: NodePort
  ports:
    - nodePort: 30019
      port: 8021
      targetPort: 8021
