apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pc-crontab
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pc-crontab
    spec:
      containers:
      - name: pc-crontab
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/pc-crontab:v1.1.3
        ports: 
        - containerPort: 8027
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: pc-crontab-svc
spec:
  selector:
    run: pc-crontab
  type: NodePort
  ports:
    - nodePort: 30023
      port: 8027
      targetPort: 8027
