apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: app-system
    spec:
      containers:
      - name: app-system
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/app-system:v1.1.3
        ports: 
        - containerPort: 8010
      imagePullSecrets:
      - name: k8slogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: app-system-svc
spec:
  selector:
    run: app-system
  type: NodePort
  ports:
    - nodePort: 30026
      port: 8010
      targetPort: 8010
