apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: app-api
    spec:
      containers:
      - name: app-api
        image: registry.cn-hangzhou.aliyuncs.com/beautybond/app-api:v1.1.56-test
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: k8simagelogindocker
---
apiVersion: v1
kind: Service
metadata:
  name: app-api-svc
spec:
  selector:
    run: app-api
  type: NodePort
  ports:
    - nodePort: 30036
      port: 8080
      targetPort: 8080
